const express = require('express');
const bodyParser = require('body-parser');
const mysql = require('mysql2');
const morgan = require('morgan');
const cors = require('cors');
var fs = require('fs');
var multer = require('multer');
// var upload = multer({ dest: 'upload/' });
var storage = multer.diskStorage(
    {
        destination: 'upload/',
        filename: function ( req, file, cb ) {
            //req.body is empty...
            //How could I get the new_file_name property sent from client here?
            cb( null, file.originalname);
        }
    }
);

var audioStorage = multer.diskStorage(
    {
        destination:'audio/',
        filename: function ( req, file, cb ) {
            console.log("FILENAME RECEIVED ",file.originalname)
            cb( null, file.originalname);
        }
    }
)

var upload = multer( { storage: storage } );
var upload1 = multer({storage : audioStorage});

const connection = mysql.createPool({
    host:'localhost',
    user:'root',
    password:'toor',
    database:'main'
})

const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
var urlencodedParser = bodyParser.urlencoded({ extended: false })  


app.use(cors());
app.use(morgan('dev'));


app.post('/insert',function(req,res) {
    connection.getConnection(function(err,connection) {
        var string = req.body.title;
        connection.query('insert into category(label) values(?)',string,function(err,results,fields) {
            if(err)
                throw err;
            res.send(results);
        })
        if(err)
            throw err;
    })
})

app.get('/getInfo',function(req,res){
    connection.getConnection(function(err,connection) {
       
        connection.query('select * from category ',function(err,results,fields) {
            if(err)
                throw err;
            console.log("Results = ",results);
            res.send(results);
        })
        if(err)
            throw err;
    })
})

app.post('/upload',upload.single('fileData'), (req, res,next) => {
    console.log("UPLOADING IMG");
    console.log(req.file);//this will be automatically set by multer
    console.log(req.body);
    //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
    fs.readFile(req.file.path,(err, contents)=> {
     if (err) {
     console.log('Error: ', err);
    }else{
     console.log('File contents ',contents);
    }
   });
  });


app.post('/uploadAudio',upload1.single('audio'),(req,res,next) => {
    console.log("in upload Audio");

    const  obj = JSON.parse(JSON.stringify(req.body));
    console.log(obj);
    const  obj1 = JSON.parse(obj.name);
    console.log(obj1);
    let fileName = obj.fileName + '.wav';
    let bluf = Buffer.from(obj1.data,'base64');
    console.log(bluf);
    fs.writeFileSync(fileName, bluf);
    
 
})

app.post('/storeData',upload1.single('allData'),(req,res,next) => {
    console.log("IN store data");
    const  obj = JSON.parse(JSON.stringify(req.body));
    console.log(obj);

    var imageName = obj.imageName;
    var categoryName = obj.category;
    var audioName = obj.audioName;
    connection.getConnection(function(err,connection) {
       
        connection.query("insert into records(" +  "imageName, " + "categoryName, " + "audioName) values(?,?," + "?)"  ,[imageName,categoryName,audioName],function(err,results,fields) {
            console.log("In query");
            if(err)
                throw err;
            console.log("Results = ",results);
            res.send(results);
        })
        if(err)
            throw err;
    })
})
app.listen(3001, () => {
    console.log('Go to http://localhost:3001/insert so you can see the data.');
   });
